require:
  - rubocop-rake
  - rubocop-rspec
  
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - spec/**/*_spec.rb

Layout/LineLength:
  Max: 180

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/wrest/components/mutators/base_spec.rb

Naming/VariableNumber:
  Exclude:
    - Gemfile

