require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - lib/active_support/**/*
    - vendor/**/*

Layout/LineLength:
  Max: 180

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/wrest/components/mutators/base_spec.rb

Lint/EmptyBlock:
  Exclude:
    - spec/wrest/callback_spec.rb

Lint/UselessAssignment:
  Exclude:
    - spec/**/*_spec.rb

Metrics/BlockLength:
  CountAsOne: [ 'array', 'heredoc', 'hash' ]
  Exclude:
    - Rakefile

Metrics/MethodLength:
  CountAsOne: [ 'array', 'heredoc', 'hash' ]
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/*.rb

Metrics/AbcSize:
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/factories.rb

Metrics/ClassLength:
  Exclude:
    - lib/wrest/uri.rb
    - lib/wrest/native/response.rb
    - spec/sample_app/lib/sample_app.rb

Metrics/ParameterLists:
  MaxOptionalParameters: 4

Naming/ClassAndModuleCamelCase:
  Exclude:
    - lib/wrest/xml_mini/*.rb

Naming/ConstantName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/wrest/native/response.rb

Naming/VariableNumber:
  Exclude:
    - Gemfile

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: [ 'array', 'hash', 'heredoc' ]
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/wrest/cache_proxy_spec.rb

RSpec/NestedGroups:
  Max: 6

RSpec/PredicateMatcher:
  Exclude:
    - spec/wrest/components/container_spec.rb
    - spec/wrest/components/container/alias_accessors_spec.rb

RSpec/StubbedMock:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashLikeCase:
  Exclude:
    - examples/facebook_auth/facebook_auth.rb
    - examples/wow_realm_status.rb
