require:
  - rubocop-rake
  - rubocop-rspec
  
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'hash']
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/*.rb

Metrics/AbcSize:
  Exclude:
    - spec/**/*_spec.rb

Layout/LineLength:
  Max: 180

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/wrest/components/mutators/base_spec.rb

Lint/EmptyBlock:
  Exclude:
    - spec/wrest/callback_spec.rb

Lint/UselessAssignment:
  Exclude:
    - spec/**/*_spec.rb

Naming/ConstantName:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - Gemfile

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/wrest/cache_proxy_spec.rb